### ISSUE TITLE
Allow deleting deselected files

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent#806]
Say a torrent contains 10 files of 1GB each, but you only want to download two of them. How do you save disk space by deleting the other eight?

Currently, you can choose which files WebTorrent will download, but (as far as I can tell) there's no way to prevent the library from creating and holding an open file descriptor for all 10 files on disk.

Just closing the file descriptor for deselected files might be enough. That allows users of the library to then delete the file themselves.

**Comment by dcposch** [comment]
@feross

**Comment by Wingman4l7** [comment]
Deselect would have to be working, first: #164

**Comment by kireerik** [comment]
In the current version I have a related issue. Storage space for deselected files are allocated. Is this already fixed in the development version?

**Comment by kocoten1992** [comment]
@kireerik , have you tried dcposch solution on 164? It'll allocate 0 on file size :+1:

**Comment by kireerik** [comment]
Hi @kocoten1992, I have tried something like that and sometimes it works, sometimes not.

Also torrents are starting immediately and there is no option for not to start torrents automatically when I add a new one.

Currently I am not actively using WebTorrent because it produced irrelevantly high download statistics on the torrent site that I am using. Maybe because it usually checks downloaded files again and again on start. Is this another bug in WebTorrent?

**Comment by feross** [comment]
> @kireerik Currently I am not actively using WebTorrent Desktop because it produced irrelevantly high download statistics on the torrent site that I am using. Maybe because it usually checks downloaded files again and again on start. Is this another bug in WebTorrent Desktop?

This bug might have been fixed in `webtorrent` by not sending the 'complete' event when we successfully reverify the torrent data, since it's only supposed to be sent once. This fix hasn't made it into a WebTorrent Desktop release yet, but it will shortly.

**Comment by kireerik** [comment]
I see, and thank you for the information!

Do you have a plan about releasing a new build for WebTorrent Desktop soon?

**Comment by feross** [comment]
Yes, there will be a new release soon.

**Comment by kireerik** [comment]
Now I have version 0.18.0 installed, but the previously described 3 issues still exist.

**Comment by kolya182** [comment]
Really need this functionality.
